### ISSUE TITLE
PDF webservice not working

### ISSUE THREAD

**Issue by YayLife** [trailheadapps/ecars#10]
I have deployed everything correctly but when I try to call the PDF webService from the UI, it returns a 503 error.

![image](https://user-images.githubusercontent.com/25455271/97102673-c1b2c480-16a7-11eb-9cdd-37345f44d64f.png)

**Comment by crcastle** [comment]
Hi @YayLife thanks for reporting this. Can you share the logs from the Heroku “services” app? That’s what generates the PDF. If you used the default app names, it should start with “ecars-serv”.

Here’s the CLI command to see the logs. Please run this right after you get that error.

`heroku logs --app=[APP NAME]`

Replace [APP NAME] with your app name. Thanks!

**Comment by YayLife** [comment]
Sure will check the logs and report it back.

**Comment by crcastle** [comment]
Thanks, @YayLife. Also let me know which car options you selected. Hopefully there's not a bug with specific combinations, but it's possible.

Also, here's what the notification should look like when it works correctly. I just tested it on a new deploy. It does take about 10 seconds to generate the PDF and show the notification. We should probably add a spinner to indicate that the user should wait.
<img width="573" alt="CleanShot 2020-10-28 at 11 48 08@2x" src="https://user-images.githubusercontent.com/275734/97460978-a5b35b00-1913-11eb-9ffe-1c8f2fc7aacb.png">

**Comment by rclark-provar** [comment]
I'm assuming the above PR fixed this issue and it can be closed? Would like to know before I reinstall. BTW replicated this issue by pushing the ecars Salesforce app to another org than the one it was created with.
