### ISSUE TITLE
Automated Download Fail

### ISSUE THREAD

**Issue by mayankagarwal900** [trailheadapps/ecars#145]
I have followed the steps for the Automated download.
on these step "git clone git@github.com:trailheadapps/ecars.git" my console(command prompt) throws the error.

"git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

so I switched on the git clone https URL.
it successfully clone the repo.
now on the last step it was failed showing these error.

" if (config.fatal) throw e;
                        ^

Error: exec: error: unknown option `show-current' ".
Please anyone, can help on these error.

**Comment by crcastle** [comment]
Hi @mayankagarwal900 - can you check which version of git you have? You can do that by running git --version

I believe you need at least version 2.22 to use the show-current subcommand.

Also, this article might help with the permission denied error you were getting, but it sounds like you got by that. https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey

**Comment by mayankagarwal900** [comment]
@crcastle Thanks for your quick reply and it has solved my previous error.
But while proceeding the further from the automated deploy it shows the error.

"spawnSync sfdx ENOENT" .

So I switched into the manual deploy somehow I completed all the steps. And application is running. But in one step its shows the error can you please help on that point also.
step is running these command 

"heroku run 'cd packages/ecars-db && npx sequelize db:migrate' --app=[STREAMING APP NAME]"

and error is 

" »   Error: Missing required flag:
  »     -a, --app APP  parent app used by review apps
  »   See more help with --help "

Thanks

**Comment by crcastle** [comment]
Hi @mayankagarwal900- When you run that command, did you replace `[STREAMING APP NAME]` with the name of your heroku app that manages the streaming data?

**Comment by mayankagarwal900** [comment]
@crcastle Yes I have done that.
