### ISSUE TITLE
Set "SF_LOGIN_URL" parameter to the "ecars-pwa" Heroku app

### ISSUE THREAD

**Issue by cverhaest** [trailheadapps/ecars#180]
**What is missing from the application? Please describe.**
Currently the "ecars-pwa" app can only works with a Scratch Org as the Salesforce Login Url is hardcoded in the "api.js" file as below:
const conn = new jsforce.Connection({
    loginUrl: 'https://test.salesforce.com'
});

**Describe the solution you'd like**
It could be great to modify the code based on a parameter (as this is already the case for the "microservice" app).
I made the modification on my side as below:

const conn = new jsforce.Connection({
    loginUrl: process.env.SF_LOGIN_URL
});

It would really help using the app with a Salesforce Production Org. Thank you

Cyril Verhaest - Salesforce Distinguished Architect

**Comment by julianduque** [comment]
@cverhaest Thank you very much! Good catch, I'll update the `ecars-pwa` to accept a `SF_LOGIN_URL`

**Comment by julianduque** [comment]
@cverhaest changes has been made on the `ecars-pwa` app and to the deploy script. Thank you very much for your report!
