### ISSUE TITLE
Why is this needed

### ISSUE THREAD

**Issue by banderson5144** [trailheadapps/ecars#214]
I am trying to understand why it is needed to ["copy"](https://github.com/trailheadapps/ecars/blob/main/apps/ecars-pwa/scripts/copySldsAssets.js) the SLDS assets from the `node_modules` folder into the assets directory. This feels a little janky. Why can we not just reference the SLDS npm package in the `lwc.config.json` file here https://github.com/trailheadapps/ecars/blob/main/apps/ecars-pwa/lwc.config.json

**Comment by msrivastav13** [comment]
@banderson5144 The `lwc.config.json` is there to specify module resolution for LWC components and third-party LWC components (Like https://www.npmjs.com/package/lightning-base-components). The third-party components should be exposed as LWC.

The SLDS bundle is not an LWC Component or Exposed as a CSS-only Module (CSS-only modules for SLDS will be overkill and cause performance bottlenecks) and hence we need to copy the SLDS assets. 

Let me know if you have any other queries on this.

**Comment by msrivastav13** [comment]
@banderson5144 Can we close this?

**Comment by banderson5144** [comment]
Yes you may.
