### ISSUE TITLE
Vehicle 'Change Status' not Updated on 'Inventory' without Browser Refresh

### ISSUE THREAD

**Issue by jeffolmstead** [trailheadapps/ecars#216]
**What is missing from the application? Please describe.**
1. Log into Salesforce (Pulsar app) 
2. Go to Inventory (e.g. /lightning/n/Inventory) 
3. Click on any of the vehicles (e.g. V-000000) 
4. Click on "Change Status" to make the status different
5. Return to Inventory and the change will not be displayed (without a browser refresh)

I am guessing it has to do with Lightning caching and not knowing the record itself has changed.

**Describe the solution you'd like**
Ideally Inventory view would refresh the status when it changes, maybe it doesn't have to be dynamic (as it is when you change status on an individual vehicle and it updates any other user of the change in real time) but at least when you come back to the page it would show the updated status.

**Additional context**
If I get any time to dig into it and get it resolved, I will push information back here.

**Comment by julianduque** [comment]
Thanks @jeffolmstead again for your detailed report! We will take a look and provide a solution.
