### ISSUE TITLE
Update LWC Jest and tests following wire protocol reform

### ISSUE THREAD

**Issue by pozil** [trailheadapps/ecars#284]
Jest LWC  benefits from a wire protocol reform that requires some [test code changes](https://github.com/salesforce/wire-service-jest-util/blob/master/docs/migrating-from-version-2.x-to-3.x.md).<br/>See [this PR](https://github.com/trailheadapps/automation-components/pull/129) for a practical example.

**Comment by julianduque** [comment]
Thanks @pozil, I'll take a look.

**Comment by julianduque** [comment]
All dependencies got updated, including this one.
