### ISSUE TITLE
Error with 'Generating lead' and 'PDF' services

### ISSUE THREAD

**Issue by PseudoDarwinist** [trailheadapps/ecars#372]
### Summary

On the eCar Heroku web app , creating a new car request gives error
On the platform, pdf service gives error
### Steps To Reproduce:

On various Lightning inputs ,selected the car configuration and click on 'Contact Me',
On salesforce platform try creating a pdf
It gives bad server error

### Expected result

It should have created a lead in salesforce
It should have generated a pdf

### Actual result

it toasts an bad server error "Your Subscription failed"
It toasts a 503 service unavailable
### Additional information
<img width="786" alt="Screenshot 2021-09-07 at 10 29 13" src="https://user-images.githubusercontent.com/25994471/132312192-4697f3cd-c581-4ec5-a3c1-6b49f968f056.png">

<img width="768" alt="Screenshot 2021-09-07 at 10 23 23" src="https://user-images.githubusercontent.com/25994471/132312232-0551fe43-86a0-4417-96d9-1358dfe04bf9.png">

**Comment by PseudoDarwinist** [comment]
Sorry, it's working fine.

**Comment by julianduque** [comment]
Thanks @PseudoDarwinist for letting us know, if this keeps happening please don't hesitate in re-opening the ticket.
