### ISSUE TITLE
Problems with the Automated deploy

### ISSUE THREAD

**Issue by V1JAYENDRA** [trailheadapps/ecars#48]
### Summary

Using the automated deploy script to deploy and running into this issue - deployment fails with this error - spawnSync sfdx ENOENT

### Steps To Reproduce:

1.  Installed all the prerequisites - VS code / git / sfdx / heroku cli 
2.  Executed the automated deployment instructions - node scripts/ecarsDeploy.js
3.  The script executes the - scratch org is setup successfully - when deploying to Scratch org-
after this result -  *** Pushing source to scratch org
4. Error is seen - spawnSync sfdx ENOENT

unable to install and use the sample on the scratch org. 

Please let me know for questions.

**Comment by enthuk** [comment]
Have the identical issue when following the instructions on Windows. Users on Mac OS are unaffected. Looked at the script and happening here:

```
log('*** Pushing source to scratch org');
execFileSync('sfdx', ['force:source:push'], { stdio: 'inherit' });

```

Tried executing the command manually using sfdx force:source:push -u ecars but then got a "Error  force-app\main\default\flexipages\Case_Record_Page_with_right_sidebar.flexipage-meta.xml  We couldn't retrieve the design time component information for component c:liveData." so blocked on this. 

Tried both Powershell and Terminal and no difference. Also followed instructions from other forums on updating Path but no change.

**Comment by msrivastav13** [comment]
@V1JAYENDRA @enthuk What version of Node.js are you on the windows machine? Please make sure you use the latest Node.js supported version.

Let us know if it still throwing the issue.

**Comment by V1JAYENDRA** [comment]
Thanks for your input - i had version v14.15.1 and i upgraded to v15.3.0 and still no luck - i am seeing the same issue . Please advice.
![VSCodeERROR_2020-12-09_10-46-53](https://user-images.githubusercontent.com/11523665/101588406-58df9b80-3a0c-11eb-94c4-c5d8ddd6b995.png)

**Comment by rclark-provar** [comment]
I'm using npm v 6.14.8 on both Mac OS and Windows 10. On Windows 10 it fails on Mac it errors out. My colleagues on Windows are facing the same issue.

**Comment by rclark-provar** [comment]
Node version 14.15.0 which is the LTS, will try 15.4.0 and restart the machine. Using 12.19 on my Macbook and that's happy

**Comment by rclark-provar** [comment]
Same issue after upgrading and restarting but not surprised, the error is still at the "execFileSync('sfdx', ['force:source:push'], { stdio: 'inherit' });" stage

**Comment by enthuk** [comment]
The script is failing because the push fails, the push fails because there's an issue with the liveData.js file that gets updated by the script. This causes the Case record flexipage to fail. Removing this page from the app and source deployment lets the rest of the script continue.

Having updated node version I did note that there is now an extra warning: 
(node:3740) Warning:    force-app/main/default/lwc/liveData*

**Comment by enthuk** [comment]
Looking into liveData.js I see the @track lines at the top are flagged as errors:

Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.

**Comment by rclark-provar** [comment]
Update on this from last week. Found liveData* listed in the .forceignore, odd. Don't understand why deploy script works on Mac but if you remove this entry from .forceignore and use the manual deployment instructions it works on Windows. Odd.

**Comment by msrivastav13** [comment]
@rclark-provar @enthuk  @V1JAYENDRA  We will look into it! Thanks for letting us know!

**Comment by dotdriver** [comment]
I get the same error as @V1JAYENDRA (Dec 8th comment) while installing on Windows 10 Pro with all the latest updates.

My setup is as follows:
node is v15.14.0
sdfx is sfdx-cli/7.96.0 win32-x64 node-v15.14.0
heroku is heroku/7.52.0 win32-x64 node-v12.21.0  (why is node listed here as v12.21.0? )

I'll explore suggestions by @enthuk

**Comment by jeffolmstead** [comment]
I am getting same error as others, if I find workaround will post back...

**Comment by jeffolmstead** [comment]
I was able to remove the errors by going to settings, searching for Experimental Decorators, and toggling it on as shown here:

![image](https://user-images.githubusercontent.com/1848585/116006416-2a3c1900-a5d9-11eb-8d20-32e607781e7f.png)

Still getting an error on this line of ecarsDeploy.js
```
execFileSync('sfdx', ['force:source:push'], { stdio: 'inherit' });
```
but if I just run sfdx: force:source:push in the console it works fine (e.g. Scratch Order objects are set up properly). I am not yet sure what stdio: 'inherit' does as a sync option, but I am going to test some more things and will see if I can get it to work. Will let you know what I find.

**Comment by jeffolmstead** [comment]
Another update from me on this one, in order to get the Host key verification failed issue to resolve itself, I manually ran this command in terminal:

```
git push git@heroku.com:HEROKU_MQTT_APP_NAME.git
```

replace HEROKU_MQTT_APP_NAME with whatever name you have in the environment. By doing it this way, it asked me the following:

```
The authenticity of host 'heroku.com (50.19.85.156)' can't be established.
RSA key fingerprint is SHA256:blah.
Are you sure you want to continue connecting (yes/no/[fingerprint])?yes
Warning: Permanently added 'heroku.com,50.19.85.156' (RSA) to the list of known hosts.
```

So, I believe I had to get past git confirming I wanted to accept the fingerprint. Possibly I missed that step in setting things up, not sure. Or, it is something you would have been already asked in the past if it wasn't the first time integrating with Heroku. Mentioning it here in hopes it helps someone else.

I have run into one more "error" from lines 354

```
    log('*** Provisioning Database');
    sh.exec(
        `heroku run 'cd packages/ecars-db && npx sequelize db:migrate' -a ${sh.env.HEROKU_REALTIME_APP_NAME}`,
        { silent: true }
    );
```

It threw this error:

```
exec:  »   Error: Missing required flag:
 »     -a, --app APP  parent app used by review apps
 »   See more help with --help
```

If I run the command directly it worked out fine:

```
heroku run 'cd packages/ecars-db && npx sequelize db:migrate' -a ecars-rt-random-name-78
```

So I am not yet sure why it didn't provision the database in the script, will let you know what I find.

**Comment by julianduque** [comment]
@jeffolmstead Thanks for this exhausting report, I'll go ahead and try the deploy script with the latest version of SFDX and push the proper fixes.

A couple of questions:

* What OS are you currently using?
* What version of the `heroku` cli and `sfdx` cli?
* Did you add the SSH key as described here: https://github.com/trailheadapps/ecars#ssh-key-for-heroku-deploys

**Comment by jeffolmstead** [comment]
@julianduque hope the comments are useful! I don't want to bog things down, but I know I find them useful if I have a similar problem and someone has detailed out the steps they took to get past it.

Here is a response to your request:
OS is: Windows 10
Heroku is: heroku/7.52.0 win32-x64 node-v12.21.0
sdfc is: sfdx-cli/7.98.0 win32-x64 node-v15.14.0
I did add SSH keys but later, I think that took care of one of my issues

One other issue I had was in generating the PDF in the ecars-services app. The script for "copy-files" wasn't copying over any folder / file that had a space in it on Heroku (worked fine locally). I ended up switching to 'ncp' package (instead of 'copyfiles' package) and now have this in my package.json (under scripts):

```
        "copy-images": "ncp routes/pdf/images dist/routes/pdf/images",
        "copy-fonts": "ncp routes/pdf/fonts dist/routes/pdf/fonts",
        "copy-files": "npm run copy-images && npm run copy-fonts",
```

And of course this in my package.json (under dependencies):

```
        "ncp": "^2.0.0",
```

This worked out good on Heroku and I was able to generate a PDF after redeploying. 

Currently, the PWA app works perfectly locally. When I click "Contact Me" it generates the Lead in Salesforce and brings in the car configuration. It also works with Push Notifications. However, on Heroku, when I click "Contact Me" I get this error thrown:

![image](https://user-images.githubusercontent.com/1848585/116256182-f2e87c00-a740-11eb-9a7e-b1ae84c66215.png)

I am still debugging that one. 

Thanks for putting together this example, it shows a lot of great integrations.

**Comment by julianduque** [comment]
@jeffolmstead for that last error, it would be useful to see if there is any output on the JavaScript developer console on your browser, also, to know what browser are you using in this case.

**Comment by jeffolmstead** [comment]
@julianduque so I just jumped over to Chrome to try it out and... it worked perfectly. 

Chrome: Version 90.0.4430.93 (Official Build) (64-bit)

I have been doing my actual work in Brave (which is based on Chrome) and here are those details:

Brave: Version 1.23.73 Chromium: 90.0.4430.85 (Official Build) (64-bit)

The Console log in Brave shows this:

Service Worker and Push is supported
app.js?__WB_REVISION__=45917dfb0f353a22dfaf20480dde5659:1 Service Worker is registered ServiceWorkerRegistration
app.js?__WB_REVISION__=45917dfb0f353a22dfaf20480dde5659:1 ServiceWorkerRegistration
app.js?__WB_REVISION__=45917dfb0f353a22dfaf20480dde5659:1 Subscribed: false
app.js?__WB_REVISION__=45917dfb0f353a22dfaf20480dde5659:1 Service worker active
app.js?__WB_REVISION__=45917dfb0f353a22dfaf20480dde5659:1 BKEoox-Ctic9c0_W5VtMasn8JaeGAcx51W9O9tHj_-2c02lDwI7jvHQN6UHFgvl2XiPf_6VVCRsSmqDDnRr0gdQ

Then for the next section a picture might be better:
![image](https://user-images.githubusercontent.com/1848585/116262674-bb7cce00-a746-11eb-88b8-370d11c1c8bb.png)

It also works fine in Edge, might just be something with my Brave browser... overall, tremendous progress!

**Comment by julianduque** [comment]
@jeffolmstead Thank you very much! This is super useful for us.

Yes, Brave might be a bit jealous and should be blocking something around WebPush Notifications, need to give it a try.

Also, thanks for recommending `npc`, I'm going to see if I can reproduce the issues you mentioned with folders with a space in their name.

Last question from me.

What shell are you using on Windows 10? It is WSL/WSL2? Are you doing it directly on Powershell or cmd.exe? Or any other like git bash?

**Comment by jeffolmstead** [comment]
I did get the same error to throw on Chrome now. When I 'Unsubscribe' it says it is successful, then when I try to 'Subscribe' again it fails with that same error. When I do a browser refresh it still shows as subscribed. So I am wondering if the 'Unsubscribe' process isn't quite working right. 

I am doing everything through Visual Studio Code and running in Node.js. I don't believe it is using a Windows Subsystem but perhaps Visual Studio Code is obfuscating that on me. I am running all commands via PowerShell (inside Visual Studio Code). And yes, to explore Heroku files (which is how I located the images missing that had spaces) I use Bash via this command 

```
heroku run bash -a {appname}
$ cd dist/routes/pdf/images/PDF
$ dir
```

And in there I could see that images were missing. Oh, one more note, to make errors easier to surface in Heroku, I added this line in 'ecars-services/routes/pdf/index.ts' on line 50
```
this.log.error(err); // Log errors to console so I can see in Heroku
```

The next line uses this:
```
request.log.warn(err.message);
```

but there is nothing on "err.message", just "err" so it didn't prove to be helpful.

**Comment by jeffolmstead** [comment]
@julianduque do you think we could align some of the lightning components with the SLDS grid so it works in mobile? Currently it doesn't work on small screens. However, if you add this markup:

![image](https://user-images.githubusercontent.com/1848585/116289262-58983080-a760-11eb-8cae-63a275fdcb3e.png)

(note the class names) AND you remove the "overflow: hidden;" on the body tag 

![image](https://user-images.githubusercontent.com/1848585/116289529-9006dd00-a760-11eb-8f6e-fed2fd637d74.png)

Then it looks excellent (I am biased I know) in mobile:
![image](https://user-images.githubusercontent.com/1848585/116289640-a876f780-a760-11eb-9eae-659c53b1792c.png)

By the way, thanks for the help, I am going to try and work through the other trailheadapps provided.

**Comment by julianduque** [comment]
@jeffolmstead Yes, that it's totally doable and a great suggestion, if you want to open PR, feel free to do it. If not, we can take care after researching the issues you have been experimenting with Windows.

I just tried the full deployment process in MacOS and it works good, so I guess there might be some slight incompatibilities on Windows.

**Comment by julianduque** [comment]
@jeffolmstead @V1JAYENDRA Thanks again for reporting this issue. Automated deployment has been fixed on Windows both on `cmd.exe` and `PowerShell`. 

@jeffolmstead The other suggestions made in this comment are going to be addressed too. Thank you again for your exhaustive report and suggestions!
