### ISSUE TITLE
Deploy to Heroku Buttons not working

### ISSUE THREAD

**Issue by YayLife** [trailheadapps/ecars#7]
Clicking on Deploy button to heroku says no app.json file is found in root directory
![image](https://user-images.githubusercontent.com/25455271/96501195-4fc61f80-1250-11eb-9774-14b4799fc0e2.png)

**Comment by crcastle** [comment]
Thanks for catching this @YayLife! Fix coming shortly.

**Comment by julianduque** [comment]
Thank you very much @crcastle for the quick fix! and @YayLife for reporting :)
