### ISSUE TITLE
Unable to push the source code to the scratch org

### ISSUE THREAD

**Issue by vibinsebastian** [trailheadapps/ecars#85]
**Summary**

When I try to push the ecars source code to the newly created scratch org. I am getting the below error:

force-app\main\default\flexipages\Case_Record_Page_with_right_sidebar.flexipage-meta.xml  We couldn't retrieve the design time component information for component c:liveData.

**Steps To Reproduce:**

1. Clone the ecars application.
2. Create a new scratch org from the dev hug org.
3. Push the source code to the scratch org. 

**Expected result**

Should be able to push the source code.

**Actual result**

Unable to push the source to the scratch org.

**Additional information**

![ecars error 1](https://user-images.githubusercontent.com/22290302/102012593-48635400-3d71-11eb-8b03-4aaabce3e5b5.PNG)

**Comment by vibinsebastian** [comment]
Adding to the above, I tried removing the c:liveData reference in the Case_Record_Page_with_right_sidebar.flexipage-meta.xml and then tried to push the source to the scratch org. 

Now, I am getting the below error:

force-app\main\default\flexipages\Case_Record_Page_with_right_sidebar.flexipage-meta.xml  The facet Facet-c727db8e-413a-4345-880d-f057274fc2c0 is defined by a component in the FlexiPage but not actually used.

Upon removing the above, I am able to successfully push the source to the scratch org.

Thanks

**Comment by msrivastav13** [comment]
@vibinsebastian can you try now and let us know if the recent changes fixed it?
